graph TD;
    RegistryInterface-->Registry;
    Chaingeareable-->Registry;
    ERC721Token/OZ-->Registry;
    SplitPaymentChangeable-->Registry;
    SplitPayment/OZ-->SplitPaymentChangeable;
    RegistryPermissionControl-->Chaingeareable;

    Pausable/OZ-->RegistryPermissionControl;
    Ownable/OZ-->SplitPaymentChangeable;
