FROM swaggerapi/swagger-ui:v3.12.1

COPY docs/markets.v1.yaml /usr/share/nginx/html/

ENV API_URLS='[                                              \
    {name:"Markets API", url:"markets.v1.yaml"}                \
]'
