graph TD;
    IDatabase-->DatabaseV1;
    OpenZeppelin.ERC721Token-->DatabaseV1;
    OpenZeppelin.SplitPayment-->DatabaseV1;
    DatabasePermissionControl-->DatabaseV1;
    OpenZeppelin.SupportsInterfaceWithLookup-->DatabaseV1;
    OpenZeppelin.ERC165-->OpenZeppelin.SupportsInterfaceWithLookup;
    OpenZeppelin.Pausable-->DatabasePermissionControl;
    OpenZeppelin.Ownable-->DatabasePermissionControl;
    OpenZeppelin.Ownable-->OpenZeppelin.Pausable;
    OpenZeppelin.Ownable-->DatabaseV1;
    OpenZeppelin.Ownable-->OpenZeppelin.SplitPayment;
    OpenZeppelin.ERC721-->OpenZeppelin.ERC721Token;
    OpenZeppelin.ERC721BasicToken-->OpenZeppelin.ERC721Token;
    OpenZeppelin.ERC721Basic-->OpenZeppelin.ERC721BasicToken;
    OpenZeppelin.ERC721Basic-->OpenZeppelin.ERC721;
    OpenZeppelin.ERC721Enumerable-->OpenZeppelin.ERC721;
    OpenZeppelin.ERC721Metadata-->OpenZeppelin.ERC721;
