graph TD;
    ERC721Token/OZ-->Chaingear;
    SplitPaymentChangeable-->Chaingear;
    ChaingearCore-->Chaingear;
    SplitPayment/OZ-->SplitPaymentChangeable;
    Ownable/OZ-->SplitPaymentChangeable;
    RegistryBase-->ChaingearCore;
    Destructible/OZ-->ChaingearCore;
    Pausable/OZ-->ChaingearCore;
