graph TD;
    IChaingear-->Chaingear;
    OpenZeppelin.ERC721Token-->Chaingear;
    OpenZeppelin.SplitPayment-->Chaingear;
    OpenZeppelin.Pausable-->Chaingear;
    OpenZeppelin.SupportsInterfaceWithLookup-->Chaingear;
    OpenZeppelin.ERC165-->OpenZeppelin.SupportsInterfaceWithLookup;
    OpenZeppelin.Ownable-->OpenZeppelin.SplitPayment;
    OpenZeppelin.Ownable-->OpenZeppelin.Pausable;
    OpenZeppelin.Ownable-->Chaingear;
    OpenZeppelin.ERC721-->OpenZeppelin.ERC721Token;
    OpenZeppelin.ERC721BasicToken-->OpenZeppelin.ERC721Token;
    OpenZeppelin.ERC721Basic-->OpenZeppelin.ERC721BasicToken;
    OpenZeppelin.ERC721Basic-->OpenZeppelin.ERC721;
    OpenZeppelin.ERC721Enumerable-->OpenZeppelin.ERC721;
    OpenZeppelin.ERC721Metadata-->OpenZeppelin.ERC721;
